### ISSUE TITLE
hello, please publish a new release

### ISSUE THREAD

**Issue by fanlia** [vesoft-inc/nebula-python#102]
hello, friends.

current version (nebula2-python==2.0.0.post1 from https://pypi.org) seems not work with latest nebula2,

`node.get_id()`, `relationship..start_vertex_id()` and `relationship..end_vertex_id()` will throw error.

current master branch is ok.

so will you publish a new release recently?

thanks.

**Comment by wey-gu** [comment]
Dear @fanlia ,

Please note the nebula2-python version is `nebula2-python==2.0.0` instead of `nebula2-python==2.0.0.post1`

We are sorry that from PyPi (https://pypi.org/project/nebula2-python/2.0.0/) `2.0.0.post1` was marked as the latest, which is actually not the case.

Please refer to README which I quoted as below.

> ## How to choose nebula-python
>
> | Nebula2-Python Version | NebulaGraph Version |
> |---|---|
> | 2.0.0.post1  | 2.0.0beta |
> | 2.0.0rc1  | 2.0.0-rc1 |
> | 2.0.0  | >= 2.0.0 |


I verified that it's working:

```bash
pip install nebula2-python==2.0.0
```

```python
>>> from nebula2.mclient import MetaCache
>>> from nebula2.sclient.GraphStorageClient import GraphStorageClient
>>> meta_cache = MetaCache([('172.18.0.2', 9559),('172.18.0.3', 9559),('172.18.0.4', 9559)],50000)
>>> graph_storage_client = GraphStorageClient(meta_cache)
>>> resp = graph_storage_client.scan_vertex('basketballplayer',tag_name='player')
>>> while resp.has_next():
...     result = resp.next()
...     for vertex_data in result:
...         print(vertex_data)
...
("player124" :player{name: "Rajon Rondo", age: 33, name1: __NULL__})
("player127" :player{name: "Vince Carter", age: 42, name1: __NULL__})
("player132" :player{name: "Giannis Antetokounmpo", age: 24, name1: __NULL__})
("player135" :player{name: "Damian Lillard", age: 28, name1: __NULL__})
("player146" :player{name: "Dwight Howard", age: 33, name1: __NULL__})
("player147" :player{name: "Amar'e Stoudemire", age: 36, name1: __NULL__})
("player148" :player{name: "Jason Kidd", age: 45, name1: __NULL__})
("player249" :player{name: "player249", age: 12, name1: "player249"})
("player103" :player{name: "Rudy Gay", age: 32, name1: __NULL__})
("player113" :player{name: "Dejounte Murray", age: 29, name1: __NULL__})
...# note, I removed some lines here
>>> vertex_data.get_id()
"player138"
>>> node = vertex_data.as_node()
>>> node.get_id()
"player138"


>>> resp = graph_storage_client.scan_edge('basketballplayer',edge_name='serve')
>>> while resp.has_next():
...     result = resp.next()
...     for edge_data in result:
...         print(edge_data)
...
("player112")-[:serve@0{start_year: 2015, end_year: 2017}]->("team204")
("player112")-[:serve@0{start_year: 2019, end_year: 2019}]->("team219")
("player112")-[:serve@0{start_year: 2017, end_year: 2019}]->("team226")
("player117")-[:serve@0{start_year: 2009, end_year: 2019}]->("team200")
("player119")-[:serve@0{start_year: 2016, end_year: 2019}]->("team200")
("player119")-[:serve@0{start_year: 2007, end_year: 2016}]->("team205")
("player134")-[:serve@0{start_year: 2009, end_year: 2018}]->("team207")
("player134")-[:serve@0{start_year: 2018, end_year: 2019}]->("team224")
...# note, I removed some lines here
>>> edge_data.as_relationship()
("player136")-[:serve@20042012{start_year: 2004, end_year: 2012}]->("team214")
>>> relationship = edge_data.as_relationship()
>>> relationship.start_vertex_id()
"player136"
>>> relationship.end_vertex_id()
"team214"
```

**Comment by wey-gu** [comment]
@laura-ding could we somehow possibly make `2.0.0` marked as latest in PiPy instead of the `*post1` to avoid this?

**Comment by fanlia** [comment]
I got it, thank you for so fast response!

**Comment by laura-ding** [comment]
> @laura-ding could we somehow possibly make `2.0.0` marked as latest in PiPy instead of the `*post1` to avoid this?

@wey-gu the order of package in pypi use the package name, no the publish date, we can modify the package name of `*post1`.

**Comment by wey-gu** [comment]
> > @laura-ding could we somehow possibly make `2.0.0` marked as latest in PyPi instead of the `*post1` to avoid this?
> 
> @wey-gu the order of package in pypi use the package name, no the publish date, we can modify the package name of `*post1`.

Aha, got it, it's in dictionary order. For now, maybe we upload/release one with 2.0.1 then to avoid renaming existing packages?
