### ISSUE TITLE
Is the connection of 2.0 thread safe?

### ISSUE THREAD

**Issue by ownthink** [vesoft-inc/nebula-python#109]
nebula 2.0的连接是否是线程安全的？

**Comment by Aiee** [comment]
The connection is not thread-safe, though the connection pool is thread-safe.

**Comment by ownthink** [comment]
我记得1.0是加锁的，2.0是否可以处理下呢

**Comment by wey-gu** [comment]
> 我记得1.0是加锁的，2.0是否可以处理下呢

If you use connection_pool, it comes with a lock already

ref: https://github.com/vesoft-inc/nebula-python/blob/master/nebula2/gclient/net/__init__.py

**Comment by ownthink** [comment]
不用pool的是否可以加锁下呢

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vesoft-inc/nebula-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula-python] nebula 2.0的连接是否是线程安全的？ (#109)





  
我记得1.0是加锁的，2.0是否可以处理下呢
  
If you use connection_pool, it comes with a lock already
 
ref: https://github.com/vesoft-inc/nebula-python/blob/master/nebula2/gclient/net/__init__.py

**Comment by laura-ding** [comment]
> 不用pool的是否可以加锁下呢 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "vesoft-inc/nebula-python" ***@***.***&gt;; 发送时间:&nbsp;2021年5月26日(星期三) 下午2:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [vesoft-inc/nebula-python] nebula 2.0的连接是否是线程安全的？ (#109) 我记得1.0是加锁的，2.0是否可以处理下呢 If you use connection_pool, it comes with a lock already ref: https://github.com/vesoft-inc/nebula-python/blob/master/nebula2/gclient/net/__init__.py — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You can look at this PR https://github.com/vesoft-inc/nebula-python/pull/67. See if it meets your needs

**Comment by ownthink** [comment]
&nbsp;目前安装的这个版本









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vesoft-inc/nebula-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vesoft-inc/nebula-python] nebula 2.0的连接是否是线程安全的？ (#109)





  
不用pool的是否可以加锁下呢 &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "vesoft-inc/nebula-python" @.&gt;; 发送时间:&nbsp;2021年5月26日(星期三) 下午2:48 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [vesoft-inc/nebula-python] nebula 2.0的连接是否是线程安全的？ (#109) 我记得1.0是加锁的，2.0是否可以处理下呢 If you use connection_pool, it comes with a lock already ref: https://github.com/vesoft-inc/nebula-python/blob/master/nebula2/gclient/net/__init__.py — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
You can look at this PR #67. See if it meets your needs

**Comment by laura-ding** [comment]
> 目前安装的这个版本，是否可以更新下pip ![image](https://user-images.githubusercontent.com/13991775/119624383-aa090d80-be3b-11eb-8710-2026f8902c58.png)

 pip install nebula2-python==2.0.0

**Comment by ownthink** [comment]
thk

**Comment by laura-ding** [comment]
Problem resolved, so close it.
