### ISSUE TITLE
API Documentation request

### ISSUE THREAD

**Issue by knwng** [vesoft-inc/nebula-python#111]
Hello everyone, do you have plan to provide API documentation? Maybe just something generated by sphinx like this http://supervisord.org/. I'm willing to help if that's in your roadmap.

**Comment by wey-gu** [comment]
This is a quite good idea, and we will also for sure benefit from the outcome when `__doc__` are being added in a way that makes sphinx happy.
We may need to align with doc teams as it requires also hooks and places to host sphinx-generated contents.

What do you think please? @laura-ding @whitewum 
Maybe we could further do similar things for all util labs?

**Comment by wey-gu** [comment]
done with #286
