### ISSUE TITLE
[feat] run test ci when upstream  repo update

### ISSUE THREAD

**Issue by yihong0618** [vesoft-inc/nebula-python#115]
![image](https://user-images.githubusercontent.com/15976103/122317591-642df980-cf50-11eb-9dff-f61c91bc5a64.png)

Because this `CI` depends on the upstream repo. 
So `CI` may failed when the upstream repo changed.

we can add some `curl` command when then upstream update trigger this `CI`

something like 
```shell
curl -H "Content-Type:application/json" -X POST -d '{"inputs": {}, "ref":"main"}' https://api.github.com/repos/yihong0618/2021/actions/workflows/${id}/dispatches -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
``` 

The api workflow doc [here](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event)

**Comment by wey-gu** [comment]
Thank you @yihong0618!

It's indeed a decent approach to make event-driven tests triggered by upstream code change when there is such dependency on the master to address i.e. thrift change caused failures.

@laura-ding what do you think?

**Comment by laura-ding** [comment]
@yihong0618 Thanks for your advice. I think adding a schedule  task to run CI is ok.
