### ISSUE TITLE
session执行了错误的语句时无法提示错误信息

### ISSUE THREAD

**Issue by zifeiYv** [vesoft-inc/nebula-python#128]
如题所述，当用session.execute()执行一个错误的语句时，返回值是一个空的`ResultSet`，如果能将错误信息返回，对于调试程序来说将会有极大的便利。

**Comment by HarrisChu** [comment]
可以校验 ResultSet 的 `is_succeeded`，如果不是 true 的话，错误信息是 error_msg()

https://github.com/vesoft-inc/nebula-python/blob/master/nebula2/data/ResultSet.py#L59

**Comment by zifeiYv** [comment]
感谢回复

**Comment by zifeiYv** [comment]
感谢回复
