### ISSUE TITLE
metad服务地址转成127.0.0.1

### ISSUE THREAD

**Issue by yangdasen1** [vesoft-inc/nebula-python#156]
graph_storage_client = GraphStorageClient(meta_cache)代码会把我填的服务器地址转成127.0.0.1，导致无法在本地上运行，只能在服务器上运行，这个要怎么解决？

**Comment by wey-gu** [comment]
storageD 的地址是从 metaD 里获取的，而源头是 storageD 自己的配置，然后会被 metaD 服务发现出来的，如果是的话，请把 storageD 的配置修改一下，改成你的客户端可以访问的网络的地址哈~~。
