### ISSUE TITLE
ONLY  PYTHON-SDK SHOWS ONLY-INCREASING-MEMORY-CURVE WHEN USING "with connection_pool.session_context(username, password) as session" EXECUTE

### ISSUE THREAD

**Issue by saksim** [vesoft-inc/nebula-python#183]
Hello everyone.

When I use python-sdk for constructiong graph with the official demo says option 2:  "with connection_pool.session_context(username, password) as session",  It actually seems released dramatically session while sometimes few of session exists as alive.

The most import issuse is the monitor-curve shows my server host get OUT OF MEMORY exception, which leads to the whole service down.

Is there anyone give any hints for this?

1) each session.execute(SQL) finished, then this session is released, but sometimes didnot
2) i only use one python-script with eventlet.monkey_patch() for asyo,  each batch 3000 points & 9000 edges at most. It seems extremely slow for building a graph with only three kinds of edge with each atmost 1 million;
3) WHY OOM occurs?

**Comment by Aiee** [comment]
> It actually seems released dramatically session while sometimes few of session exists as alive.
Could you be more specific on this? Did you mean connection instead of the session?

1. If the session is requested from `connection_pool.session_context()`, it should always release the connection
2. We recommend using nebula-importer/nubula-exchage to import relative large data
3. Is there any log? What was the query running?

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
