### ISSUE TITLE
raise RuntimeError( RuntimeError: The services status exception: [services: ('127.0.0.1', 9669), status: BAD]

### ISSUE THREAD

**Issue by SaqlainHussainShah** [vesoft-inc/nebula-python#205]
Nebula services are running
`[INFO] nebula-metad: Running as 49784, Listening on 9559
[INFO] nebula-graphd: Running as 49847, Listening on 9669
[INFO] nebula-storaged: Running as 49873, Listening on 9779
`
However the following code to connect to nebula graph as mentioned on github page
`from nebula3.gclient.net import ConnectionPool
from nebula3.Config import Config

# define a config
config = Config()
config.max_connection_pool_size = 10
# init connection pool
connection_pool = ConnectionPool()
# if the given servers are ok, return true, else return false
ok = connection_pool.init([('127.0.0.1', 9669)], config)`

gives 

>  raise RuntimeError(
RuntimeError: The services status exception: [services: ('127.0.0.1', 9669), status: BAD]

**Comment by SaqlainHussainShah** [comment]
Further

**Comment by Aiee** [comment]
Hi, It seems you are connecting the Nebula service with an incompatible python client. Please make sure the versions match.
