### ISSUE TITLE
是否支持异步操作 async/await? 

### ISSUE THREAD

**Issue by kevinkelin** [vesoft-inc/nebula-python#206]
我查看之前某个版本合并了一个pr, 有提到支持async操作,但是在最新的master分支上已经没有

请问是否有支持异步操作的nebula3-python 计划？

**Comment by Aiee** [comment]
We currently have no plan to support async operations. However, you could manage a session pool yourself to simulate the async process, and please be aware that one session can only be used by one thread at the same time.
