### ISSUE TITLE
请问我用python执行  session.execute(cmd)   有没有办法看出来是否执行成功呢？

### ISSUE THREAD

**Issue by tyn513** [vesoft-inc/nebula-python#220]
请问我用python执行  session.execute(cmd)   有没有办法看出来是否执行成功呢？
python执行后一点提示都没有，都不知道执行的情况。py2neo会直接报错

Is there any way to see if I executed session.execute(CMD) in Python?
Python executes without any hint of what's going on. Py2neo will simply report an error

**Comment by wey-gu** [comment]
执行的返回是一个 resultSet 里边有执行的结果哈，出错也有error code 的

**Comment by wey-gu** [comment]
closing it
