### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by Hydrion-Qlz** [vesoft-inc/nebula-python#225]
这个有对应的API文档吗

**Comment by wey-gu** [comment]
还没有哈，可以参考 https://github.com/vesoft-inc/nebula-python/tree/master/example

**Comment by Hydrion-Qlz** [comment]
好的，还有是想问一下对于GQL语句是否单独封装了函数，还是说只能通过`execute`函数执行原始GQL语句

**Comment by wey-gu** [comment]
> 好的，还有是想问一下对于GQL语句是否单独封装了函数，还是说只能通过`execute`函数执行原始GQL语句

现在各个语言客户端没有 ORM 的封装，不过社区有一些 Nebula Graph ORM在，比如 https://github.com/zhihu/norm https://github.com/nebula-contrib/graph-ocean https://github.com/nebula-contrib/ngbatis ，python 上，目前 https://github.com/SwordElucidator/nebula-model 最有希望，可以关注一下，不过还在开始的实现中

**Comment by Hydrion-Qlz** [comment]
好的，非常感谢你的回答
