### ISSUE TITLE
Question about ConnectionPool()

### ISSUE THREAD

**Issue by doublex** [vesoft-inc/nebula-python#226]
> "... please be aware that one session can only be used by one thread at the same time ..."
> https://github.com/vesoft-inc/nebula-python/issues/206

Does "session" this mean:
* `gclient.net.ConnectionPool()` must not be shared among threads
* a connection from the `gclient.net.ConnectionPool()` is not shared among threads

More precise, is this allowed?
````python
global connection_pool = gclient.net.ConnectionPool()

def thread_1():
    global connection_pool
    ...

def thread_2():
    global connection_pool
    ...
````

**Comment by wey-gu** [comment]
Yes, it isn't thread-safe, thus we should maintain a local connection pool per thread :).

**Comment by doublex** [comment]
Dear @wey-gu 
If I create a connection-pool with e.g. 30 connections.
How can a thread query 30 GO-statements in parallel?
Best wishes from Vienna!

**Comment by wey-gu** [comment]
> Dear @wey-gu If I create a connection-pool with e.g. 30 connections. How can a thread query 30 GO-statements in parallel? Best wishes from Vienna!

Yes, you can, just ensure one session can only be used by one thread is enough.

**Comment by doublex** [comment]
I see!
Thanks for explanation!
