### ISSUE TITLE
`get_tag_schema()` returns non-decoded result

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula-python#242]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
`get_tag_schema()` returns non-decoded result

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**
Ref: https://discuss.nebula-graph.com.cn/t/topic/11447/4

**Expected behavior**

**Additional context**

**Comment by HarrisChu** [comment]
marked as known issue.

root cause:
1. meta stores the default value as `Expression`.
2. and it could not decode in python client.
