### ISSUE TITLE
What IP Address should we use when calling init method on ConnectionPool

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-python#245]
**General Question**

Can someone tell what IP Address should we use when calling init method on ConnectionPool
- Should we use graph service NodePort IP Address?
- Or, should we use IP Address of all graphd nodes?

Below code snippet is from official nebula-python release [docs](https://github.com/vesoft-inc/nebula-python)
```
# define a config
config = Config()
config.max_connection_pool_size = 10
# init connection pool
connection_pool = ConnectionPool()
# if the given servers are ok, return true, else return false
ok = connection_pool.init([('127.0.0.1', 9669)], config)
```

@wey-gu

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, is this issue been resolved? If not resolved, can you provide some more information? If solved, can you close this issue?

Thanks a lot for your contribution anyway 😊
