### ISSUE TITLE
nebula2-python SessionPool Support

### ISSUE THREAD

**Issue by liuxiaocs7** [vesoft-inc/nebula-python#246]
**General Question**

Now there is a project still using nebula2.x, is there any plan to support sessionpool in nebula2.6.0, thx

**Comment by MuYiYong** [comment]
Hi, we won't revert the session pool feature to 2.6, you can upgrade to 3.x or refer to the  session pool implementation in 3.x

Here is the reference:
https://github.com/vesoft-inc/nebula-python/blob/release-3.3/example/SessinPoolExample.py

**Comment by liuxiaocs7** [comment]
OK, thx
