### ISSUE TITLE
Do not have value attribute in the ScanEdge object gotten by StorageClient.scan_edge

### ISSUE THREAD

**Issue by autumnalK** [vesoft-inc/nebula-python#262]
I'm quite sure that I do have data in Nebula. My Nebula verison is 1.2.7 and I installed the nebula-python==1.1.0
When I refer to the StorageClientExample.py, the ScanEdge result I got has no value.

- what I do
`scan_edge_response_iterator = storage_client.scan_edge(space_name, return_cols, all_cols, limit, start_time, end_time)`
`scan_edge_response_iterator.next().edge_data[0]`
- what I get
`ScanEdge(
    src=3241934849,
    type=195,
    dst=0)`

Just want to know what wrong I may have done qwq

**Comment by QingZ11** [comment]
As we communicated in the post [https://discuss.nebula-graph.com.cn/t/topic/12240](https://discuss.nebula-graph.com.cn/t/topic/12240), we recommend you to upgrade the core and tool versions if production environment allows.

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
