### ISSUE TITLE
Query statistics

### ISSUE THREAD

**Issue by doublex** [vesoft-inc/nebula-python#263]
Is there a button to query `nebula-python` if a query was exhausting?
Nebula is never slow - but I have the impression some queries are CPU expensive.
I would like to pinpoint those.

**Comment by wey-gu** [comment]
> Is there a button to query `nebula-python` if a query was exhausting? Nebula is never slow - but I have the impression some queries are CPU expensive. I would like to pinpoint those.

Would you mind describing more on your picture of this feature? Better with some reference that other lib provided similar functions?

**Comment by doublex** [comment]
Yes, sorry.
Some query is causing a lot of CPU load on the Nebula server. 
Is there a profiler tool to find out which query it is?
My first thought was a summary-feature like:
````
result = session.execute( statement )
slow_query = result.get_stats()
````

**Comment by wey-gu** [comment]
You could go with `SHOW QUERIES`, for now, we could only see like how long they were executed.

But normally long run queries are those we need to care about, right?

**Comment by doublex** [comment]
@wey-gu 
Thanks for everything!!

**Comment by doublex** [comment]
You put me on the right track:
https://docs.nebula-graph.io/3.4.0/3.ngql-guide/17.query-tuning-statements/1.explain-and-profile/
Best wishes!

**Comment by wey-gu** [comment]
Wow good to know it helped in some way.

Then I would recommend my blog post about this: https://www.siwei.io/ngql-execution-plan/ while it's Chinese only for now, if you can't read Chinese, I'll post the English version soon.(sorry about this)

**Comment by doublex** [comment]
@wey-gu 
Impressive! Thanks for everything!
