### ISSUE TITLE
Querying NebulaGraph using the Nebula Python API is significantly slower than using the Nebula Console.

### ISSUE THREAD

**Issue by neojoe** [vesoft-inc/nebula-python#266]
我在服务器上用docker的方式安装nebulagraph 
服务器配置：cpu 16v ，内存128g，150G ESSD云盘
执行相同的查询逻辑
nebula onsole：MATCH p = allShortestPaths((a:point{name:"13644:5"})-[e*..7]-(b:point{name:"5119:1"}))  RETURN p;
查询时间是700ms左右
![image](https://user-images.githubusercontent.com/20881163/222115948-a6d29e18-9d0c-41f3-b63f-2e5d73175a0c.png)
而用nebula python  api 执行相同的逻辑，花费65s
![image](https://user-images.githubusercontent.com/20881163/222116844-de5d2d97-0d5e-4c93-818e-d16ebe8e06ae.png)
请问是什么原因？

**Comment by neojoe** [comment]
java  api 也是同样的问题

**Comment by wey-gu** [comment]
Ping @Aiee @Nicole00 is this related to serialization time, or?

**Comment by Nicole00** [comment]
> 

你可以看下console中执行结果会有两个时间，700ms 是执行结果ResultSet中的latency时间，后面那个是客户端执行的总体时间。

如果要对比其他客户端，可以通过同时对比resultSet.getLatency 或者 同时对比 客户端执行总时间 来确定各个客户端的性能差异。

**Comment by QingZ11** [comment]
@neojoe hi, if your problem is solved, would you like to close the issue? Thanks a lot for your contribution.
