### ISSUE TITLE
 The performance of using python api to query nebula is weaker than that of nebula console

### ISSUE THREAD

**Issue by neojoe** [vesoft-inc/nebula-python#267]
I installed nebulagraph on the server with docker
Server configuration: cpu 16v, memory 128g, 150G ESSD cloud disk
Execute the same query logic
nebula console: MATCH p = allShortestPaths((a:point{name:"13644:5"})-[e*..7]-(b:point{name:"5119:1"})) RETURN p;
The query time is about 700ms
![image](https://user-images.githubusercontent.com/20881163/222142826-ef99060d-a3f4-4d8f-a483-b29232263b66.png)
While using the nebula python api to execute the same logic, it takes 65s
![image](https://user-images.githubusercontent.com/20881163/222143081-5fa5aa31-6f86-4daf-a9f3-c9d1cb68f410.png)

May I ask what is the reason

**Comment by QingZ11** [comment]
https://github.com/vesoft-inc/nebula-python/issues/266

已经有相同的 issue 了，不需要开多个 issue 来讨论类似的问题哈。这边先行关闭了，你可以留意下另外个 issue 的回复，谢谢 [neojoe](https://github.com/neojoe)
