### ISSUE TITLE
If you perform an `INSERT VERTEX` operation without creating the space and tags beforehand, the vertex insertion will not be successful.

### ISSUE THREAD

**Issue by zbximo** [vesoft-inc/nebula-python#271]
**General Question**

在一个python 程序中，先create space、tag后执行insert VERTEX，插入点不会成功。报错如下：
```json
{'_decode_type': 'utf-8',
 '_resp': ExecutionResponse(
    error_code=-1009,
    latency_in_us=8559,
    space_name=b'test_final',
    error_msg=b"SemanticError: No schema found for `NodeUserInfo'"), '_data_set_wrapper': None, '_all_latency': 34602, '_timezone_offset': 0}
```
但是如果先用一个程序执行create space，tag，再用一个程序执行insert VERTEX就能成功。

**Comment by wey-gu** [comment]
这是目前的期待行为，文档里有提及，schema 更改（创建、删除、更改space、tag、index），要等最多两个心跳时间才能被更新到所有的服务本地的 schema cache 里。程序里如果设计 ddl 接着 dml ，要在 dml 之前等待一下。

**Comment by QingZ11** [comment]
@zbximo hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
