### ISSUE TITLE
renew Session for session expired & reconnect connection of session for IOError

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula-python#276]
add re-execute operation, before re-execute, we should renew the session if the failure is E_SESSION_INVALID or E_SESSION_TIMEOUT, and we should reconnect the session's connection for IO Error, and just re-execute for E_EXECUTION_ERROR.

Don't retry for E_STATEMENT_EMPTY and E_SYNTAX_ERROR.

**Comment by wey-gu** [comment]
Sure, I can do this :) @Nicole00

**Comment by wey-gu** [comment]
https://github.com/vesoft-inc/nebula-python/issues/275

**Comment by wey-gu** [comment]
like implementations from

https://github.com/jerryjliu/llama_index/blob/c528cf6857193a6056cfb2d77666ba3c5659750b/llama_index/graph_stores/nebulagraph.py#L170-L219
