### ISSUE TITLE
logging is not defined

### ISSUE THREAD

**Issue by Lincyaw** [vesoft-inc/nebula-python#277]
https://github.com/vesoft-inc/nebula-python/blob/master/nebula3/gclient/net/ConnectionPool.py

In this file, `logging` is not defined. It will be triggered when server crashed due to the large memory usage.

**Comment by wey-gu** [comment]
> https://github.com/vesoft-inc/nebula-python/blob/master/nebula3/gclient/net/ConnectionPool.py
> 
> In this file, `logging` is not defined. It will be triggered when server crashed due to the large memory usage.

Dear @Lincyaw , sorry for this! would you mind PR to replace logging with logger?

Thanks!

**Comment by Lincyaw** [comment]
https://github.com/vesoft-inc/nebula-python/pull/280 

I have created the PR~

**Comment by wey-gu** [comment]
Thanks a lot @Lincyaw for the contribution, again :D closing it.
