### ISSUE TITLE
 Storage Error: RPC failure, probably timeout.

### ISSUE THREAD

**Issue by salahaz** [vesoft-inc/nebula-python#283]
When using nebula-python to execute queries it throws:
` Storage Error: RPC failure, probably timeout.` 

This happens even though, the query is optimized using LIMIT. Here's the query: 
`match (n:malware) return n.malware.name limit 3;`

Mind you, running the exact same query in Nebula console works.

NebulaGraph is run using the nebula-docker-compose, its version is 3.6.0

All cluster containers are running and healthy; the logs don't log any specific errors.

Any ideas?

**Comment by wey-gu** [comment]
was discussed on another thread and it was resolved and thus closed.
