### ISSUE TITLE
ModuleNotFoundError: No module named 'FormatResp'

### ISSUE THREAD

**Issue by guhao17** [vesoft-inc/nebula-python#284]
当我运行test.py的时候，导入这个模块一直失败，请问怎么解决
![image](https://github.com/vesoft-inc/nebula-python/assets/116614355/93c70cbb-71e3-4dab-b4b7-05f021e2b65b)

**Comment by wey-gu** [comment]
It's a relative path from the [FormatResp.py](https://github.com/vesoft-inc/nebula-python/blob/master/example/FormatResp.py), you could either go to your python ide from that path, change the from path, or copy print_resp from https://github.com/vesoft-inc/nebula-python/blob/master/example/FormatResp.py.
