### ISSUE TITLE
Does nebula-python support bind parameters now?

### ISSUE THREAD

**Issue by MichelleMa8** [vesoft-inc/nebula-python#329]
**General Question**
Hi, 

Does nebula-python support bind parameters now? Where can I find related documentations? Or is there any other method to avoid injection attacks?

Thanks!

**Comment by wey-gu** [comment]
Yes it does!

See: https://github.com/vesoft-inc/nebula-python/blob/master/tests/test_parameter.py

Later I can prepare for more docs on this :)
