### ISSUE TITLE
Suggestions for debugging the output

### ISSUE THREAD

**Issue by gumupaier** [vesoft-inc/nebula-python#33]
If you are debugging output code, can you remove the test code, such as print() output, or use the logging module to set the output level to debug

**Comment by gumupaier** [comment]
Such as this


![image](https://user-images.githubusercontent.com/37896380/90599068-ca5dc900-e226-11ea-9d6b-a7ea50c29a95.png)

**Comment by laura-ding** [comment]
@gumupaier Thanks very much! I will delete the print.
