### ISSUE TITLE
Should Pandas be added as requirement for nebula-python?

### ISSUE THREAD

**Issue by magnudae** [vesoft-inc/nebula-python#365]
### Should pandas be added to the dependency list? 

I am playing around with the [ResultSet](https://github.com/vesoft-inc/nebula-python/blob/ba345a6e26e480201c7abe6314687f744b12bb1b/nebula3/data/ResultSet.py) in my project at the moment and I stumbled upon that if I use `as_data_frame` I get the error I need Pandas python.

I thought this would automatically come with nebula-python since its a dependency, but then I see its not in the dependency list of the project.

**Should pandas be added to the dependency list?** I see it comes down in the lock file here, but that only declares the lockfile for this project (not projects depending on this)

**Comment by wey-gu** [comment]
Thanks @magnudae , it's on-purposely not included as dep to keep nebula-python slim as the sugar of as_data_frame was considered not a mandatory user path, but we could consider adding optional profile like `pip install nebula3-python[dataframe]` to improve dx? what do you think?

**Comment by magnudae** [comment]
> Thanks @magnudae , it's on-purposely not included as dep to keep nebula-python slim as the sugar of as_data_frame was considered not a mandatory user path, but we could consider adding optional profile like `pip install nebula3-python[dataframe]` to improve dx? what do you think?

Yeah after looking at it for a little bit more, I agree with you that it should be a core dependancy, as you say, to keep it slim.

Adding the `[dataframe]` would be helpful, but I think it shouldnt be prioritised over other things

thank you @wey-gu for the answer, ill close my question here since I think it is rightfully not included in the dependency list
