### ISSUE TITLE
About code notes

### ISSUE THREAD

**Issue by gumupaier** [vesoft-inc/nebula-python#43]
Can scan_vertex() give some notes? I run the example directly and report the following error
![image](https://user-images.githubusercontent.com/37896380/92122811-81189680-ee2e-11ea-8721-63abb0d3bb3d.png)

**Comment by jievince** [comment]
> MetaClient(["172.254.221.194", 3699)])

3699 is graph server listening port, but meta server listening port is needed here.
BTW, you don't need to change of the StorageClientExample.py, you'd better run the example by the following command:
`python3 StorageClientExample.py meta_ip meta_port space_name_to_read`
For example:
`python3 StorageClientExample.py 192.168.8.16 45500 nba`
192.168.8.16 is the ip of meta server,
and 45500 is the port of meta server.

**Comment by haloxzt** [comment]
Hi bro,  I run the example directly and got the report as following.
![image](https://user-images.githubusercontent.com/45658716/98217273-3a0d6580-1f85-11eb-96ff-fb3db18cd8ee.png)
How to solve this? thank u.

And,  this is only code i changed
![image](https://user-images.githubusercontent.com/45658716/98218905-4a264480-1f87-11eb-873a-583bba3fff9f.PNG)

**Comment by gumupaier** [comment]
High probability is a network problem, refer to this
[https://discuss.nebula-graph.com.cn/t/topic/1211/35](https://discuss.nebula-graph.com.cn/t/topic/1211/35)

**Comment by laura-ding** [comment]
Problem resolved, so close it
