### ISSUE TITLE
pip install nebula2-python failed

### ISSUE THREAD

**Issue by bochuxt** [vesoft-inc/nebula-python#69]
pip install --upgrade pip
Collecting pip
  Downloading pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.8 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-20.3.3
(venv3) sin-l-00040531:nebula-python ghu$ pip install nebula2-python
Collecting nebula2-python
  Using cached nebula2-python-2.0.0.post1.tar.gz (208 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/ghu/venv3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-njme8vo5/nebula2-python_ce8687f99fac4defa2066899ce5bd31b/setup.py'"'"'; __file__='"'"'/private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-njme8vo5/nebula2-python_ce8687f99fac4defa2066899ce5bd31b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-pip-egg-info-ocjnz21x
         cwd: /private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-njme8vo5/nebula2-python_ce8687f99fac4defa2066899ce5bd31b/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-njme8vo5/nebula2-python_ce8687f99fac4defa2066899ce5bd31b/setup.py", line 9, in <module>
        from setuptools import setup, find_packages, sic
    ImportError: cannot import name 'sic' from 'setuptools' (/Users/ghu/venv3/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zealot-shin** [comment]
same problem:
solved by upgrading setuptools:
pip install --upgrade setuptools -i https://xxxxxxxx

**Comment by laura-ding** [comment]
> same problem:
> solved by upgrading setuptools:
> pip install --upgrade setuptools -i https://xxxxxxxx

Thanks, I think it useless, I will delete it.

**Comment by laura-ding** [comment]
Dependency has been removed, so close it.
