### ISSUE TITLE
git clone git@github.com:vesoft-inc/nebula-python.git  Report an error

### ISSUE THREAD

**Issue by zdYng** [vesoft-inc/nebula-python#7]
$ git clone git@github.com:vesoft-inc/nebula-python.git
Cloning into 'nebula-python'...
The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,13.229.188.59' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

But when I use 
```
git clone https://github.com/vesoft-inc/nebula-python.git
```
is ok

**Comment by zdYng** [comment]
[root@test python-client]# git clone https://github.com/vesoft-inc/nebula-python.git
Cloning into 'nebula-python'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 187 (delta 3), reused 7 (delta 2), pack-reused 175
Receiving objects: 100% (187/187), 213.26 KiB | 89.00 KiB/s, done.
Resolving deltas: 100% (63/63), done.

**Comment by whitewum** [comment]
Thank you for your report

**Comment by laura-ding** [comment]
has been modified in #14
