### ISSUE TITLE
利用python连接nebula环境可以通 ，但是不管执行任何语句都报错

### ISSUE THREAD

**Issue by Gaoeggplant** [vesoft-inc/nebula-python#74]
ResultSet(ExecutionResponse(
    error_code=-5,
    latency_in_us=0))

**Comment by laura-ding** [comment]
> ResultSet(ExecutionResponse(
> error_code=-5,
> latency_in_us=0))

Could you post the code you use? Did you initialize the pool with multiple Graphd addresses? If so, When use the`get_session()`, set retry_connect=False, may be is cause the reconnect to different graphd, and the handle of reconnect in graphd is not ready

**Comment by laura-ding** [comment]
Thanks for your question. If there are no more problems, I will close this problem first, you can  reopen it when you need.
