### ISSUE TITLE
Failed to install nebula2-python-2.0.0.post1.tar.gz 

### ISSUE THREAD

**Issue by bochuxt** [vesoft-inc/nebula-python#77]
Using cached nebula2-python-2.0.0.post1.tar.gz (208 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/ghu/venv3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-datfggyz/nebula2-python_4a45945b3bf14ee6a9e458674044738a/setup.py'"'"'; __file__='"'"'/private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-datfggyz/nebula2-python_4a45945b3bf14ee6a9e458674044738a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-pip-egg-info-gv9uxp3g
         cwd: /private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-datfggyz/nebula2-python_4a45945b3bf14ee6a9e458674044738a/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/70/l0j2y_9n4r77xk73rcn3cjzh0000gp/T/pip-install-datfggyz/nebula2-python_4a45945b3bf14ee6a9e458674044738a/setup.py", line 9, in <module>
        from setuptools import setup, find_packages, sic
    ImportError: cannot import name 'sic' from 'setuptools' (/Users/ghu/venv3/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------

**Comment by liuyuru156** [comment]
通过下载文件安装的方式，可以避免这个问题

**Comment by laura-ding** [comment]
感谢您的提问。这是因为你的setuptools版本太低，没有sic。你更新setuptools的版本就可以。但是最新的代码已经删除这个使用，你用新的版本是不会有这个问题的。
