### ISSUE TITLE
This function thrift.server.CppServerWrapper was not found.

### ISSUE THREAD

**Issue by zdYng** [vesoft-inc/nebula-python#8]
![image](https://user-images.githubusercontent.com/17880611/69224282-3c7d8080-0bb7-11ea-98d0-5e312cce8fe6.png)
Did not find this file  CppServerWrapper

**Comment by whitewum** [comment]
@laura-ding

**Comment by laura-ding** [comment]
@zdYng It won't affect the use, Only the IDE display cannot be found.
