### ISSUE TITLE
访问不到ScanSpace？

### ISSUE THREAD

**Issue by Lanme** [vesoft-inc/nebula-python#82]
https://github.com/vesoft-inc/nebula-python/blob/master/example/ScanVertexEdgeExample.py

`
from nebula2.Config import Config
from nebula2.gclient.net import ConnectionPool
from nebula2.mclient import MetaCache
from nebula2.sclient.GraphStorageClient import GraphStorageClient
import random
import sys
import time

def prepare_data():
    config = Config()
    config.max_connection_pool_size = 1
    # init connection pool
    connection_pool = ConnectionPool()
    # the graphd server's address
    assert connection_pool.init([('192.168.14.8', 9669)], config)
    client = connection_pool.get_session('root', 'root')
    client.execute('CREATE SPACE IF NOT EXISTS ScanSpace('
                   'PARTITION_NUM=10,'
                   'vid_type=FIXED_STRING(20));'
                   'USE ScanSpace;'
                   'CREATE TAG IF NOT EXISTS person(name string, age int);'
                   'CREATE EDGE IF NOT EXISTS friend(start int, end int);')
    time.sleep(5)
    result = client.execute('SHOW TAGS')
    print(result)
    
    for id in range(20):
        vid = 'person' + str(id)
        cmd = 'INSERT VERTEX person(name, age) ' \
              'VALUES \"{}\":(\"{}\", {})'.format(vid, vid, id)
        client.execute(cmd)
    for id in range(20):
        src_id = 'person' + str(id)
        dst_id = 'person' + str(20 - id)
        start = random.randint(2000, 2010)
        end = random.randint(2010, 2020)
        cmd = 'INSERT EDGE friend(start, end) ' \
              'VALUES \"{}\"->\"{}\":({}, {})'.format(src_id, dst_id, start, end)
        client.execute(cmd)
    client.release()
    connection_pool.close()

def scan_person_vertex(graph_storage_client):
    resp = graph_storage_client.scan_vertex(
        space_name='ScanSpace',
        tag_name='person',
        limit=100)
    print('======== Scan vertexes in ScanSpace ======')
    while resp.has_next():
        result = resp.next()
        for vertex_data in result:
            print(vertex_data)

def scan_person_edge(graph_storage_client):
    resp = graph_storage_client.scan_edge(
        space_name='ScanSpace',
        edge_name='friend',
        limit=100)
    print('======== Scan edges in ScanSpace ======')
    while resp.has_next():
        result = resp.next()
        for edge_data in result:
            print(edge_data)
`
############################
`
meta_cache = MetaCache([('192.168.14.8', 9669)],
                       50000)
graph_storage_client = GraphStorageClient(meta_cache)
prepare_data()
scan_person_vertex(graph_storage_client)
scan_person_edge(graph_storage_client)
`
############################
![image](https://user-images.githubusercontent.com/28859589/107017716-70ec5500-67da-11eb-8a99-1cd1c344522d.png)

**Comment by laura-ding** [comment]
Thanks for your question.
Firstly `meta_cache = MetaCache([('192.168.14.8', 9669)]` here is the meta_ip and meta_port, 9669 maybe is the graphd's port.
Secondly, you need to get the config `heartbeat_interval_secs` in your graphd conf. the sleep time needs to set large than it.

**Comment by laura-ding** [comment]
@Lanme Thanks for your question, if you have any questions, you can reopen it. Now I close it.
