### ISSUE TITLE
ScanVertexEdgeExample.py can't find storage ip

### ISSUE THREAD

**Issue by wc188996** [vesoft-inc/nebula-python#83]
The meta_server is 192.168.61.185:4455,storage_server is 192.168.61.185:6655,and nebula_graph is 192.168.61.185:7755
I've used the correct meta_server's ip:port.
`meta_cache = MetaCache([('192.168.61.185', 4455)],50000)`
`graph_storage_client = GraphStorageClient(meta_cache)`
`prepare_data()`
but the error is 
`[2021-02-07 13:26:59,966]:Create storage connection failed: socket error connecting to host 127.0.0.1, port 6655 (('127.0.0.1', 6655)): ConnectionRefusedError(61, 'Connection refused')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nebula2_python-2.0.0rc1-py3.9.egg/nebula2/fbthrift/transport/TSocket.py", line 279, in open
    handle.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused`

pyclient got the loopback address 127.0.0.1:6655, not 192.168.61.185:6655

**Comment by laura-ding** [comment]
Thanks for your question. Could you give the result of execute `SHOW HOSTS`. Maybe the `local_ip` in your storage conf file is set `127.0.0.1`

**Comment by wc188996** [comment]
> Thanks for your question. Could you give the result of execute `SHOW HOSTS`. Maybe the `local_ip` in your storage conf file is set `127.0.0.1`

There is a '127.0.0.1' ip binded ,how can i delete it from the binding?
`[2021-02-07 16:03:05,525]:Get connection to ('192.168.61.185', 6677)
ResultSet(keys: ['Host', 'Port', 'Status', 'Leader count', 'Leader distribution', 'Partition distribution'], values: ["127.0.0.1", 6655, "OFFLINE", 0, "No valid partition", "space_thread0:100, space_thread1:100, space_thread2:100, space_thread3:100"],["192.168.61.185", 6655, "ONLINE", 0, "No valid partition", "No valid partition"],["Total", __EMPTY__, __EMPTY__, 0, __EMPTY__, "space_thread0:100, space_thread1:100, space_thread2:100, space_thread3:100"])
`

**Comment by laura-ding** [comment]
After 24 hours later. the 127.0.0.1 will be deleted, but your spaces are all in 127.0.0.1, the data can't be read. You can see https://discuss.nebula-graph.com.cn/t/topic/2442, it tells how to make the data point to the new IP when the corresponding IP of space is changed.

**Comment by wc188996** [comment]
> After 24 hours later. the 127.0.0.1 will be deleted, but your spaces are all in 127.0.0.1, the data can't be read. You can see https://discuss.nebula-graph.com.cn/t/topic/2442, it tells how to make the data point to the new IP when the corresponding IP of space is changed.

Thanks! I will check the connection yesterday.
