### ISSUE TITLE
[trivial] Introduce contextmanager for ConnectionPool?

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-python#84]
Dear,

Do you think it makes sense to enable getting a connection from ConnectionPool with context manager support?

In most cases, the Session.__del__() already takes care of it for us to release the session when the local Session being recycled, which is great. While still there is a chance in a long routine, where explicitly releasing session could be missing by the end-users. To provide a context manager enabled method to support `with statement` could be one way forward like:

```python
with connection_pool.session_context('root', 'nebula') as session:
    session.execute('USE nba')
    result = session.execute('SHOW TAGS')
    print(result)
```

A draft PR for this trivial change is here: #85 

Please reject it if it's a silly idea/design :-p. If you consider it's an accepted way to go, I'll be more than happy to continue polishing the PR.
Thanks!

BR, Wey

**Comment by Aiee** [comment]
Hello,

Thank you for your contribution to Nebula and welcome to the community!
Your PR was accepted thus closing this issue.
