### ISSUE TITLE
No ID in ResultSet

### ISSUE THREAD

**Issue by IbereJr** [vesoft-inc/nebula-python#91]
Hi, congratulations about your amazing database.

I am using Nebula DB v2-nightly, and Client Python V2.0.0-RC1
When I made a query in Web Console: (for example:   match(a:Datacenter) return a;  ), the response is something like:
{
  "code": 0,
  "data": {
    "headers": [
      "a"
    ],
    "tables": [
      {
        "a": "(-8898061935899072461 :Datacenter{id: \"007\", name: \"DCName\", server: \"DCServer\"})",
        "properties": {
          "Datacenter": {
            "id": "007",
            "name": "DCName",
            "server": "DCServer"
          }
        },
        "tags": [
          "Datacenter"
        ],
        "type": "vertex",
        "vid": -8898061935899072461
      },
(...   all vertex had same struture)

But, when I made the same query in python client, I had the response:

ResultSet(ExecutionResponse(
    error_code=0,
    latency_in_us=3500,
    data=DataSet(
        column_names=[b'a'],
        rows=[Row(
            values=[Value(
                vVal=Vertex(
                     tags=[Tag(
                         name=b'Datacenter',
                         props={b'id': Value(
                             sVal=b'007'),
                         b'name': Value(
                             sVal=b'DCName'),
                         b'server': Value(
                             sVal=b'DCServer')})]))]),

so... where is the vertex ID ??  (vid) ?
when  I try to print this resultset:

+------------------------------------------------------------------+
| a                                                                |
+------------------------------------------------------------------+
| {Node}([None]:{{tag_name: b'Datacenter', props: {b'name': Value( |
|     sVal=b'DCName'), b'server': Value(                         |
|     sVal=b'DCServer'), b'id': Value(                             |
|     sVal=b'007')}}})                                             |

Node is indexed by "None"... 
if in my query, I specify: match(a:Datacenter) return id(a) as ID, a  I will receive the right id in ID Column, but a colum still has "None"

**Comment by laura-ding** [comment]
@IbereJr Thanks for your question. The nebula-graph is the nightly version, the python client needs to use the master code too.

**Comment by laura-ding** [comment]
Open it again if you have any questions.
