### ISSUE TITLE
Unable to use pip3 install nebula2-python 

### ISSUE THREAD

**Issue by qingpingswiftsword** [vesoft-inc/nebula-python#99]
Using cached https://files.pythonhosted.org/packages/a9/27/0cf91580f927a2877acc9b8e00cb278cd190fdcf326861624f74ccdee647/nebula2-python-2.0.0.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-__myxa7a/nebula2-python/setup.py", line 9, in <module>
        from setuptools import setup, find_packages, sic
    ImportError: cannot import name 'sic'

**Comment by laura-ding** [comment]
You need to use the latest version,  the 2.0.0.post1 is the oldest version. You need to use `pip3 install nebula2-python=2.0.0`
